language: R
sudo: false
cache: packages
env:
  matrix:
    secure: o7S3iLxaiOTSVFhU/DOqaAaChpyhgvztkiMupBfeP96f+OYZeySEcv1cTQc91v+yHH+fX7jf81IG/09wFe+UrhQbAZyRScmKLjLb5ZLR3oXYCfRxAOuIKuy4ShtehZLSDu5kHmdAGNUQpekjOZ+7yOEf2+7kGTB6zB8ygqUBaO5sO/hs//FtRMp92BPBHIVKgC0oja/BLVKdUH1NwZpAPaEWPBPmpr5WAlwTEwg2YF8wSLht7TfB1MtqEe+kHZFQ9z3B5l6vcNdCvEosdKlglcU1LGKuRAVj2KQZavNWjz1UaPnbS2zx0fVn5VnqeUSungLsGWceSi92OUjVUoVgrJndndsVP+ZlryrAvmhazDgNfaKGxH0ipKrTJ/TzV2txOCsJEbqetDUaEbRRRr02+X54lZtImIMceHCWBsWDnA4rMI9Xs2HOwux+QumPiN64evDU40SSAeYl7RZCZRIir3ua1YRjVZDt3Z1iwUwTyAnm3/BpPEr30UtTs/QFn/z8VOgdz8DKLvi9HMLt8Iz3dwLg5aaIcWJWXP++DWW64q6n+CNpxNq9wu+z6e9gVuzYFDfjpjXZ6RE9g+I/Pm0utcDnri2Lr80Lu8cKy+fsGzXtWHGhzMe17JnfeD5QI4RLmS3IKLCtBBhYpOuWXFbedYa4PahfV0IzJqowVvcZ6gk=
