language: R
sudo: false
cache: packages
env:
  matrix:
    secure: ZWVaf65kKNC0/5de5N/QmH6BJy4V/5vrzGgMz0i1fGOudp/me71NoAP8zTlV5zGnC2byuKTjAv+upbZJG6IUWSBxQvjgZNtEiFLQgnIdmhkmpA6xeApCVM60BA0EF9qL8/1P/KF3T9xOL5I91T5NuXKhmLf78hJXveCvIlELOUW9/4ECOCmWLhxIC6qYbM9rDhCgXWBol52uGOH4Jtqd+fUsRQIgcbPAejk0jk/1UWeG29tAD5f3r43GtG/7tkcpKnHmIhyauRDt9fKLafVamq2xB54RKxT5r2DCCo+pTXEBJPsWoHHpGJjWvZD7Ku/PuPTQ6wEgkVwzPdjTXjNbx4AXM8jzSqgZu+eFPjutCks+rFiC+NEKfTP5iEVflwuVOVK11i5BH5FWdV3HxAhH2Cuu+iZGQii8MjJYdmTmXHqgcnaQx96sg7fFWq0F/C8AV0FpZEWXdRt5Cd30Tpso85bgQQWIFmuU2ElWgKGouAqe9+Vo+TS5bmuG928rNUjLBBJ3UyCzcsscQTOeyeyAuZXN3gmwB48fKSiOQMykqlzpIgrZrqSZjAaXWyoKwsBFizVHf0QIxdbrINoBF8pmRkXQe8oAyVCEIR6orrA4vuZt6hMWlXr2H2csXsrVpA6rqDxUp7dJbrT4j6JwgyRDzKmuTIhggtkkBTOER0a79ig=
